export enum Actions {
  UPDATE_USER_PREFERENCE = "UPDATE_USER_PREFERENCE",
  UPDATE_SELECTED_CATEGORY = "UPDATE_SELECTED_CATEGORY",
  ADD_ANSWER = "ADD_ANSWER",
  START_NEW_GAME = "START_NEW_GAME",
}
